### ISSUE TITLE
login_list and id_list defined without usage

### ISSUE THREAD

**Issue by alirezashojaei** [RwinShow/Twitch-Follower-Checker#2]
In lines 91 and 92 two list variables are defined but not used anywhere in the code. Isn't that true they will be made dynamically by lines 95 and 98?

**Comment by RwinShow** [comment]
Fixed in [05150ff](https://github.com/RwinShow/Twitch-Follower-Checker/pull/3/commits/05150fffcf7ce3f680e981064c5fdf0480b2c5d8).
